name: Test model build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - access-esm1.5
  push:
    branches:
      - master
      - access-esm1.5

jobs:
  build:
    name: Build ${{ github.repository }} via spack
    uses: access-nri/build-ci/.github/workflows/model-1-build.yml@main
    permissions:
      packages: read
